from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from . import views
#from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('student_register/' , views.student_register , name='student_register'),
    path('student_login/', views.student_login,name='student_login'),
    path('dept_register/' , views.dept_register , name='dept_register'),
    path('dept_login/', views.dept_login,name='dept_login'),
    # path('dept/dept_login/dispstu1/',views.dispstu1,name='dispstu1'),
    # path('dept/dept_login/usd1/',views.usd1,name='usd1'),
    path('student_login/usd/',views.usd,name='usd'),
    path('logout/', views.pagelogout, name='logout'),
    path('student_login/dispstu/',views.dispstu,name='dispstu'),
    
    path('', views.home, name='home'),
   
    path('contact/',views.contact,name='contact'),
    path('about/',views.about,name='about'),
    path("password_reset/", views.password_reset_request, name="password_reset"),

    path('student_login/myresume',views.myresume,name='myresume'),
    path('student_login/displayResume',views.displayResume,name='displayresume'),
    # path('student_login/resume/',views.resume,name="resume"),
    path('student_login/apply',views.student_companyApplied,name='apply'),
    path('student_login/placementPrep/',views.placementPrep,name='PP'),
    path('quizindex/',views.quizindex,name='quizindex'),
    path("<int:myid>/", views.quiz, name="quiz"), 
    path('<int:myid>/data/', views.quiz_data_view, name='quiz-data'),
    path('<int:myid>/save/', views.save_quiz_view, name='quiz-save'),
    path('add_quiz/', views.add_quiz, name='add_quiz'),    
    path('add_question/', views.add_question, name='add_question'),  
    path('add_options/<int:myid>/', views.add_options, name='add_options'), 
    path('results/', views.results, name='results'),    
    path('delete_question/<int:myid>/', views.delete_question, name='delete_question'),  
    path('delete_result/<int:myid>/', views.delete_result, name='delete_result'),    
    path('student/student_login/offerletter',views.offerletter,name='Upload'),
    path('view',views.show_file,name='view'),
    path('student_login/placementPrep/java',views.java,name='java'),
    path('student_login/placementPrep/c',views.c,name='c'),
    path('student_login/placementPrep/dbms',views.Dbms,name='dbms'),
    path('student_login/placementPrep/cn',views.Cn,name='cn'),
    path('student_login/placementPrep/algo',views.Algo,name='algo'),
    path('student_login/placementPrep/os',views.Os,name='os'),
    path('student_login/placementPrep/ds',views.Ds,name='ds'),
    path('student_login/placementPrep/others',views.Other,name='others'),
    path('dept_register/' , views.dept_register , name='dept_register'),
    path('dept_login/', views.dept_login,name='dept_login'),
    path('dept_login/index/',views.index, name='index'),
    path('dept_login/index1/',views.index1, name='index1'),
    path('dept_login/index2/',views.index2, name='index2'),
    path('dept_login/index3/',views.index3, name='index3'),
    path('dept_login/index4/',views.index4, name='index4'),
    path('dept_login/index5/',views.index5, name='index5'),
    path('dept_login/index6/',views.index6, name='index6'),
    path('dept_login/index7/',views.index7, name='index7'),
    path('dept_login/index1/upload1/',views.upload1,name='upload1'),
    path('dept_login/index2/upload2/',views.upload2,name='upload2'),
    path('dept_login/index3/upload3/',views.upload3,name='upload3'),
    path('dept_login/index4/upload4/',views.upload4,name='upload4'),
    path('dept_login/index5/upload5/',views.upload5,name='upload5'),
    path('dept_login/index6/upload6/',views.upload6,name='upload6'),
    path('dept_login/index7/upload7/',views.upload1,name='upload1'),
    path('dept_login/index/upload/',views.upload,name='upload'),
    path('student_login/display/',views.display,name='display'),
]
